### ISSUE TITLE
UI of landing page and editor .

### ISSUE THREAD

**Issue by adi-rajput** [aialok/codehub#1]
The UI is not suitable for user it is too much vibrant , and user must be given functionality to choose day and night mode.

![Screenshot 2024-05-15 171513](https://github.com/aialok/codehub/assets/123539586/a2ad6160-bea0-455f-b58a-e3bf97ae4148)

**Comment by aialok** [comment]
Nice, Thank you for your issue @adi-rajput .

Will Work on it : )

**Comment by adi-rajput** [comment]
Hey @aialok  is the issue resolved as per the requirement?

**Comment by aialok** [comment]
> Hey @aialok is the issue resolved as per the requirement?

Thank you Aditya for the issue. Currently I have some other priorities will back to it when I have free time.
